name: promotions
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.9.1
  flutter_bloc: ^9.1.1
  share_plus: ^11.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  drift: ^2.27.0
  flutter_svg: ^2.2.0
  intl: ^0.20.2
  auto_route: ^10.1.0+1
  get_it: ^8.0.3
  internet_connection_checker_plus: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  drift_dev: ^2.27.0
  auto_route_generator: ^10.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/vectors/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600
